trainings:
  - title: Substance Use Disorders in Young Populations
    date: 2026-09-30
    startTime: 11:00
    endTime: 12:30
    trainer: Jean Bagnati, LCSW, LICSW
    format: virtual
    location: Zoom
    ceus: 1.5
    credits:
      - 1.5 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 1.5 NBCC-approved continuing education credit hours
      - Approved for 1.5 NAADAC CE Hours
    description: Substance Use Disorders (SUD) can affect any population,
      adolescents and young adults included. This population can present
      uniquely and treatment needs to be individualized for these
      considerations. This training will inform of the prevalence of SUDs within
      this population, the risk factors and contributing causes from a societal
      perspective, the correlation with co-occurring mental health conditions,
      and screening measures. This training will also discuss the multiple
      pathways for wellness and how these can increase treatment engagement and
      willingness with this population.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_vOOqKU44TDSeFQCMAUyjjg#/registration
  - title: Identification and Treatment of Peripartum Depression and Anxiety Disorders
    date: 2026-10-06
    startTime: 12:00
    endTime: 14:00
    note: TRAINING ALMOST AT CAPACITY--REGISTER SOON!
    trainer: Zobeida Diaz, MD, MS
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: This training will provide an overview of peripartum depression and
      anxiety disorders, including their prevalence, risk factors, and the
      importance of early identification. Participants will explore biological
      factors that may contribute to these conditions and review current
      evidence regarding the effectiveness and safety of antidepressant
      medications during pregnancy and lactation. The training will also
      introduce emerging and novel treatment options for postpartum depression.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_zqK-oRscRY-MWaZ7wMvrtQ
  - title: "Talk, Laugh, Heal: Group Therapy for the Brave"
    date: 2026-10-19
    startTime: 12:00
    endTime: 14:00
    trainer: Roxxanne Newman, PhD Candidate, MA, CPRS
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: This course provides an in-depth exploration of group counseling
      techniques and their application in addiction treatment. Attendees will
      learn theoretical foundations, evidence-based practices, and facilitation
      skills necessary to lead effective group counseling sessions. The course
      emphasizes ethical considerations, cultural competency, and the role of
      group dynamics in the recovery process.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_IzjrAZOuTxqcjcgdhYKKJw
  - title: Building Cultural Competency in Behavioral Health
    date: 2026-10-30
    startTime: 09:00
    endTime: 12:00
    trainer: Fran DaLomba, MSW, LICSW
    format: virtual
    location: Zoom
    ceus: 3
    credits:
      - 3.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 3.0 NBCC-approved continuing education credit hours
      - Approved for 3.0 NAADAC CE Hours
    description: This interactive training is designed to help behavioral health
      professionals provide more culturally responsive and equitable care.
      Participants will explore the impact of culture, bias, communication, and
      social determinants of health on client engagement and outcomes while
      learning practical strategies to improve self-awareness, strengthen
      therapeutic relationships, and reduce health disparities. Through
      discussion, reflection, case studies, and interactive activities,
      participants will gain skills they can immediately apply to better serve
      individuals from diverse backgrounds.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_MOefcrUBQa6fSEF2zFUcCA
  - title: Best Practices in Clinical Documentation
    date: 2026-11-13
    startTime: 09:00
    endTime: 11:00
    trainer: Nompelelo Boucher, PhD.
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: Understand the ethical and multicultural issues associated with
      assessment, treatment and clinical documentation. To learn about the Five
      Steps to Competent Clinical Documentation such as case conceptualization.
      Conceptualize the presenting issue with the help of theory and client’s
      lived experience. To learn the importance of using assessment tools to
      understand the client’s mental status, risk assessment and symptom
      severity to support medical necessity. Take into consideration issues of
      social justice, multicultural experiences, as well as attention to issues
      of diversity, equity, and inclusion. In the treatment planning phase focus
      on measurable goals and assessing for other services needed to support
      treatment. Evaluating progress towards identified goals. This training
      will also focus on how to document crisis and risk management issues,
      supervision, case consultation, and collateral contacts. We will use case
      examples to discuss the tone of documentation such as writing in an
      objective, observational and dispassionate tone to decrease the use of
      personal judgement, biases, interpretations, and derogatory remarks.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_R8X-PMPdT2S_sJxOwtGX_w
  - title: "Women in Recovery: Pathways to Healing and Empowerment"
    date: 2026-11-17
    startTime: 12:00
    endTime: 14:00
    trainer: Roxxanne Newman, PhD Candidate, MA, CPRS
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: This course explores the unique challenges and experiences of women
      in substance use recovery. It examines biological, psychological, and
      sociocultural factors affecting recovery, and emphasizes trauma-informed
      care, resilience, and empowerment. From this lecture, attendees will
      develop a comprehensive understanding of best practices in supporting
      women on their recovery journey.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_Lh9WzICcTYWbJqAxc44wOg
  - title: Navigating Mental Health & Wellness–Tools for a Balanced Life
    date: 2026-12-01
    startTime: 13:00
    endTime: 14:30
    trainer: Meaghan Levasseur
    format: virtual
    location: Zoom
    ceus: 1.5
    credits:
      - 1.5 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
    description: In this workshop, participants will recognize the potential risk
      factors and warning signs for a range of mental health problems including
      depression, anxiety/trauma, psychotic disorders, substance abuse disorders
      & self-injury. The training will also review action plans, review the
      latest data on various mental health disorders, and explore resources
      available.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_sBx89KzdS261fBJ1XDQ0Xw#/registration
  - title: "Mental Health Parity 101: Legal Framework and Tools for Healthcare
      Providers"
    note: Date to be announced
    trainer: Shamus Durac
    format: virtual
    location: Zoom
    ceus: 1
    credits:
      - 1.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 1.5 NBCC-approved continuing education credit hours
      - Approved for 1.5 NAADAC CE Hours
    price: $8
    description: This talk, the first part in a series of two, will provide an
      introduction and overview of federal and state mental health parity law
      for healthcare providers. We will review the requirements of MHPAEA, the
      federal parity law, as well as Rhode Island state parity law, and the
      health insurance regulatory framework within which those laws apply. We
      will discuss some common types of parity violations, how those violations
      are identified, and how healthcare providers can help protect their
      patients' access to needed behavioral healthcare.
    registerUrl: https://www.trainedprogram.net/challenge-page/8849daaf-ba64-4b3a-a64f-b9d72e049956?programId=8849daaf-ba64-4b3a-a64f-b9d72e049956
  - title: "Leadership 2.0: Mastering The 7 Roles of The Clinical Supervisor"
    date: 2027-01-13
    startTime: 10:00
    endTime: 12:00
    trainer: Mark Sanders, LCSW, CADC
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    registerUrl: https://us06web.zoom.us/webinar/register/WN_AJgJi_KMQUCJXGV9AVC-WA
  - title: Trauma Informed Care for Individuals with Developmental Disabilities
    date: 2027-01-13
    startTime: 12:00
    endTime: 14:00
    trainer: Francis Tierney, CSW
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: Participants will explore how individuals with intellectual and
      developmental disabilities, particularly Autism, experience and respond to
      trauma in unique ways. Participants will learn about specific expressions
      of trauma for people with developmental disabilities that are affected by
      sensory and communication differences. We will apply trauma informed
      principles and pre-existing clinical skills to learn how to better support
      participants in clinical spaces.
    registerUrl: https://us06web.zoom.us/webinar/register/WN_WAf5PYevQjCmTGPM5zfsew
  - title: Youth Suicide Assessment & Intervention Strategies
    date: 2027-01-19
    startTime: 10:00
    endTime: 12:00
    trainer: Tom Butero, LICSW
    format: virtual
    location: Zoom
    ceus: 2
    credits:
      - 2.0 CEUs (National Association of Social Workers – RI Chapter, RI
        Certification Board Chemical Dependency, and Licensed Mental Health
        Counselors through the RI Mental Health Counselors Association)
      - 2.0 NBCC-approved continuing education credit hours
      - Approved for 2.0 NAADAC CE Hours
    description: Program will include information on risk assessment strategies for
      youth who are contemplating suicide and intervention techniques to prevent
      a suicide attempt or after a non-completed attempt. Contracting for safety
      and post-vention strategies will also be discussed
    registerUrl: https://us06web.zoom.us/webinar/register/WN_M0gNZXBwTeeWKU0k4ySbaQ
